package com.familyfinance.loan;

import com.familyfinance.asset.*;
import com.familyfinance.category.*;
import com.familyfinance.family.*;
import com.familyfinance.household.*;
import com.familyfinance.ledger.*;
import com.familyfinance.shared.*;
import java.math.BigDecimal;
import java.time.*;
import java.util.*;
import org.springframework.data.domain.*;
import org.springframework.security.core.Authentication;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service @Transactional(readOnly = true)
public class LoanService {
    private static final int MAX_PAGE_SIZE=50;
    private final LoanRepository loans; private final AssetRepository assets; private final FamilyMemberRepository members; private final AppUserRepository users;
    private final FinancialAccountRepository accounts; private final CategoryRepository categories; private final AssetService assetService; private final CurrentMembership current; private final FamilyMutationAuthorization mutations; private final Clock clock;
    private final AmortizationCalculator calculator=new AmortizationCalculator();
    LoanService(LoanRepository loans, AssetRepository assets, FamilyMemberRepository members, AppUserRepository users, FinancialAccountRepository accounts, CategoryRepository categories, AssetService assetService, CurrentMembership current, FamilyMutationAuthorization mutations, Clock clock) {
        this.loans=loans;this.assets=assets;this.members=members;this.users=users;this.accounts=accounts;this.categories=categories;this.assetService=assetService;this.current=current;this.mutations=mutations;this.clock=clock;
    }
    public LoanPage list(Authentication a, LoanStatus status,int page,int size){long h=current.require(a).householdId(); int p=Math.max(0,page), s=Math.min(MAX_PAGE_SIZE,Math.max(1,size)); Page<Loan> r=loans.findByHouseholdIdAndStatus(h,status==null?LoanStatus.ACTIVE:status,PageRequest.of(p,s,Sort.by(Sort.Direction.DESC,"id"))); return new LoanPage(r.stream().map(LoanResponse::from).toList(),p,s,r.getTotalElements(),r.getTotalPages(),r.hasNext());}
    public LoanResponse get(Authentication a,long id){return LoanResponse.from(find(current.require(a).householdId(),id));}
    public LoanSchedulePage schedule(Authentication a,long id,int page,int size){Loan l=find(current.require(a).householdId(),id);int p=Math.max(0,page),s=Math.min(MAX_PAGE_SIZE,Math.max(1,size));long total=l.getInstallments().size();int totalPages=(int)Math.ceil((double)total/s);List<LoanInstallmentResponse> items=l.getInstallments().stream().skip((long)p*s).limit(s).map(LoanInstallmentResponse::from).toList();return new LoanSchedulePage(items,p,s,total,totalPages,p+1<totalPages);}
    @Transactional public LoanResponse create(Authentication a,LoanCreateRequest r){var access=mutations.requireAdmin(a); Values v=validate(access.context().householdId(),r); Asset asset=v.asset; if(asset==null && Boolean.TRUE.equals(r.createAssetFromLoan())) { if(v.type==LoanType.OTHER) throw new RequestValidationException(Map.of("createAssetFromLoan","只有房产或车辆贷款可以自动创建关联资产")); asset=assetService.createLoanPurchaseAsset(access.household(),access.membership().getUser(),v.type==LoanType.MORTGAGE?AssetType.PROPERTY:AssetType.VEHICLE,v.principal,v.member,v.start); } Loan loan=new Loan(access.household(),v.name,v.type,asset,v.member,v.user,v.account,v.category,v.principal,v.rate,v.term,v.method,v.start,access.membership().getUser()); loan.replaceSchedule(v.schedule); return LoanResponse.from(loans.saveAndFlush(loan));}
    @Transactional public LoanResponse update(Authentication a,long id,LoanPatchRequest r){var access=mutations.requireAdmin(a);Loan old=find(access.context().householdId(),id);if(old.isArchived())throw new ResourceConflictException("LOAN_CLOSED","贷款已归档或结清");if(old.getInstallments().stream().anyMatch(i->i.getStatus()==LoanInstallmentStatus.PAID)){ if(hasContractField(r)) throw new RequestValidationException(Map.of("contract","已有还款记录，合同字段不可修改")); old.update(r.name()==null?old.getName():required(r.name(),"name"),old.getMember(),resolveUser(access.context().householdId(),r.assignedUserId(),old.getAssignedUser()),old.getLinkedAsset(),old.getPaymentAccount(),old.getPaymentCategory(),old.getPrincipalCents(),old.getAnnualRate(),old.getTermMonths(),old.getRepaymentMethod(),old.getStartOn(),List.of()); return LoanResponse.from(old); }
        LoanCreateRequest merged=new LoanCreateRequest(r.name()==null?old.getName():r.name(),old.getType(),r.linkedAssetId()==null?(old.getLinkedAsset()==null?null:old.getLinkedAsset().getId()):r.linkedAssetId(),r.memberId()==null?(old.getMember()==null?null:old.getMember().getId()):r.memberId(),r.assignedUserId()==null?(old.getAssignedUser()==null?null:old.getAssignedUser().getId()):r.assignedUserId(),r.paymentAccountId()==null?old.getPaymentAccount().getId():r.paymentAccountId(),r.paymentCategoryId()==null?old.getPaymentCategory().getId():r.paymentCategoryId(),r.principal()==null?Money.formatCents(old.getPrincipalCents()):r.principal(),r.annualRate()==null?old.getAnnualRate():r.annualRate(),r.termMonths()==null?old.getTermMonths():r.termMonths(),r.repaymentMethod()==null?old.getRepaymentMethod():r.repaymentMethod(),r.startOn()==null?old.getStartOn():r.startOn(),r.customSchedule()); Values v=validate(access.context().householdId(),merged); old.update(v.name,v.member,v.user,v.asset,v.account,v.category,v.principal,v.rate,v.term,v.method,v.start,v.schedule); return LoanResponse.from(old); }
    @Transactional public void archive(Authentication a,long id){var access=mutations.requireAdmin(a);Loan loan=find(access.context().householdId(),id);if(loan.getInstallments().stream().anyMatch(i->i.getStatus()==LoanInstallmentStatus.PAID))throw new ResourceConflictException("LOAN_HAS_PAYMENTS","已有还款记录的贷款不能归档");loan.archive(clock.instant());}
    private Values validate(long h,LoanCreateRequest r){Map<String,String> f=new LinkedHashMap<>(); if(r==null){throw new RequestValidationException(Map.of("request","请求不能为空"));} String name=required(r.name(),"name",f);LoanType type=r.type();if(type==null)f.put("type","贷款类型不能为空");long principal=parseMoney(r.principal(),"principal",f);BigDecimal rate=r.annualRate();if(rate==null||rate.scale()>6||rate.signum()<0||rate.compareTo(BigDecimal.ONE)>0)f.put("annualRate","年利率必须在 0 到 1 之间且最多六位小数");int term=r.termMonths()==null?0:r.termMonths();if(term<1||term>360)f.put("termMonths","期数必须在 1 到 360 之间");if(r.startOn()==null)f.put("startOn","起息日不能为空"); RepaymentMethod method=r.repaymentMethod();if(method==null)f.put("repaymentMethod","还款方式不能为空"); Asset asset=resolveAsset(h,r.linkedAssetId(),type,f); FamilyMember member=resolveMember(h,r.memberId(),f);AppUser user=resolveUser(h,r.assignedUserId(),null);FinancialAccount account=r.paymentAccountId()==null?null:accounts.findByIdAndHouseholdIdAndArchivedAtIsNull(r.paymentAccountId(),h).orElse(null);if(account==null)f.put("paymentAccountId","付款账户必须属于当前家庭且未归档");Category category=r.paymentCategoryId()==null?null:categories.findByIdAndHouseholdId(r.paymentCategoryId(),h).filter(c->c.getKind()==TransactionKind.EXPENSE).orElse(null);if(category==null)f.put("paymentCategoryId","付款分类必须是当前家庭的支出分类");if(!f.isEmpty())throw new RequestValidationException(f);List<InstallmentDraft> schedule=method==RepaymentMethod.CUSTOM?custom(r.customSchedule(),principal,term):calculator.calculate(principal,rate,term,r.startOn(),method);return new Values(name,type,asset,member,user,account,category,principal,rate.setScale(6),term,method,r.startOn(),schedule);}
    private List<InstallmentDraft> custom(List<CustomInstallmentRequest> rows,long principal,int term){if(rows==null||rows.size()!=term)throw new RequestValidationException(Map.of("customSchedule","自定义计划必须与期数相同"));List<InstallmentDraft> out=new ArrayList<>();long sum=0;LocalDate previous=null;for(int i=0;i<rows.size();i++){var r=rows.get(i);if(r==null||r.dueOn()==null||previous!=null&&!r.dueOn().isAfter(previous))throw new RequestValidationException(Map.of("customSchedule","自定义到期日必须递增"));long p;try{p=Money.parseCents(r.principal());}catch(IllegalArgumentException e){throw new RequestValidationException(Map.of("customSchedule","自定义本金格式不正确"));}long interest=r.interest()==null||r.interest().equals("0")||r.interest().equals("0.00")?0:Money.parseCents(r.interest());sum=Math.addExact(sum,p);out.add(new InstallmentDraft(i+1,r.dueOn(),p,interest,0));previous=r.dueOn();}if(sum!=principal)throw new RequestValidationException(Map.of("customSchedule","自定义本金总和必须等于贷款本金"));long remaining=principal;List<InstallmentDraft> fixed=new ArrayList<>();for(var d:out){remaining-=d.principalCents();fixed.add(new InstallmentDraft(d.installmentNo(),d.dueOn(),d.principalCents(),d.interestCents(),remaining));}return fixed;}
    private Asset resolveAsset(long h,Long id,LoanType type,Map<String,String> f){if(id==null)return null;Asset a=assets.findByIdAndHouseholdId(id,h).filter(x->!x.isArchived()).orElse(null);if(a==null){f.put("linkedAssetId","关联资产必须属于当前家庭且未归档");return null;}if((a.getType()==AssetType.PROPERTY&&type!=LoanType.MORTGAGE)||(a.getType()==AssetType.VEHICLE&&type!=LoanType.CAR)||a.getType()==AssetType.OTHER)f.put("linkedAssetId","贷款类型与关联资产类型不兼容");return a;}
    private FamilyMember resolveMember(long h,Long id,Map<String,String> f){if(id==null)return null;return members.findByIdAndHouseholdId(id,h).orElseGet(()->{f.put("memberId","成员必须属于当前家庭");return null;});}
    private AppUser resolveUser(long h,Long id,AppUser fallback){if(id==null)return fallback;return users.findByIdAndHouseholdIdAndStatus(id,h,AppUserStatus.ACTIVE).orElseThrow(()->new RequestValidationException(Map.of("assignedUserId","指派用户必须属于当前家庭且有效")));}
    private static String required(String v,String field){return required(v,field,new LinkedHashMap<>());} private static String required(String v,String field,Map<String,String> f){String n=v==null?"":v.trim();if(n.isEmpty()||n.length()>100)f.put(field,"名称不能为空且不超过 100 个字符");return n;}
    private static long parseMoney(String raw,String field,Map<String,String> f){try{return Money.parseCents(raw);}catch(IllegalArgumentException e){f.put(field,e.getMessage());return 0;}}
    private static boolean hasContractField(LoanPatchRequest r){return r.linkedAssetId()!=null||r.memberId()!=null||r.paymentAccountId()!=null||r.paymentCategoryId()!=null||r.principal()!=null||r.annualRate()!=null||r.termMonths()!=null||r.repaymentMethod()!=null||r.startOn()!=null||r.customSchedule()!=null;}
    private Loan find(long h,long id){return loans.findByIdAndHouseholdId(id,h).orElseThrow(()->new ResourceNotFoundException("贷款不存在"));}
    private record Values(String name,LoanType type,Asset asset,FamilyMember member,AppUser user,FinancialAccount account,Category category,long principal,BigDecimal rate,int term,RepaymentMethod method,LocalDate start,List<InstallmentDraft> schedule){}
}
